import type { FC, ReactElement } from 'react';
import type { TChildrenProps } from './types';
import { NextAuthProvider } from './provider';

export const metadata = {
  title: 'Nx Next App',
  description: 'Generated by create-nx-workspace',
};

const RootLayout: FC<TChildrenProps> = ({ children }): ReactElement => {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body>{children}</body>
      </NextAuthProvider>
    </html>
  );
};

export default RootLayout;
