# fly.toml app configuration file generated for mknows-fe-cs on 2023-06-13T17:59:39+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mknows-fe-cs"
primary_region = "sin"

[build]
  dockerfile = "./Dockerfile.cs"

[http_service]
  internal_port = 4200
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
