name: Docker Image Build Test

on:
  push:
    branches: [ "develop" ]

jobs:
  docker-build-kg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . --file Dockerfile.kg --tag kg:$(date +%s)
      
  docker-build-lxp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . --file Dockerfile.lxp --tag lxp:$(date +%s)
      
  docker-build-cs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . --file Dockerfile.cs --tag cs:$(date +%s)
   
