name: Docker Image Build Test

on:
  push:
    branches: [ "develop" ]

jobs:
  docker-build-kg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . --file Dockerfile.kg --tag kg:$(date +%s)
      
  docker-build-lxp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . --file Dockerfile.lxp --tag lxp:$(date +%s)
      
  docker-build-cs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . --file Dockerfile.cs --tag cs:$(date +%s)
      
  docker-build-kg-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . --file Dockerfile.kg-admin --tag kg-admin:$(date +%s)
      
  docker-build-lxp-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . --file Dockerfile.lxp-admin --tag lxp-admin:$(date +%s)
      
  docker-build-cs-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . --file Dockerfile.cs-admin --tag cs-admin:$(date +%s)

  docker-build-kg-dosen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . --file Dockerfile.kg-dosen --tag kg-dosen:$(date +%s)
   
