name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    types: [opened]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      docker-build-kg:
      - uses: actions/checkout@v3
      - name: Build Docker Image KG
        run: docker build . --file Dockerfile.kg --tag kg:$(date +%s)
    
